from rest_framework import serializers

from .models import Vendor, PurchaseOrder


class PurchaseOrderSerializer(serializers.ModelSerializer):
    vendor_name = serializers.ReadOnlyField(source='vendor.name')
    vendor_contact_details = serializers.ReadOnlyField(source='vendor.contact_details')
    vendor_address = serializers.ReadOnlyField(source='vendor.address')
    vendor_code = serializers.ReadOnlyField(source='vendor.code')
    on_time_delivery_rate = serializers.ReadOnlyField(source='vendor.on_time_delivery_rate')
    quality_rating_avg = serializers.ReadOnlyField(source='vendor.quality_rating_avg')
    average_response_time = serializers.ReadOnlyField(source='vendor.average_response_time')
    fulfillment_rate = serializers.ReadOnlyField(source='vendor.fulfillment_rate')

    class Meta:
        model = PurchaseOrder
        exclude = (
            'created_at',
            'updated_at'
        )
        read_only_fields = ('po_number',) #NOTE: This should be auto-generated by the system


class VendorSerializer(serializers.ModelSerializer):
    purchase_orders = serializers.SerializerMethodField()

    class Meta:
        model = Vendor
        exclude = (
            'created_at', 
            'updated_at'
        )
        read_only_fields = ('code',) #NOTE: This should be auto-generated by the system
    
    def get_purchase_orders(self, obj):
        return PurchaseOrderSerializer(
            obj.purchase_orders, 
            many=True
        ).data
